stages:
    - build

before_script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN

nginx:1.17:
    stage: build
    image: docker:stable
    services:
        - docker:dind
    script:
        - IMAGE_NAME_CURRENT=liteacz/cron:$CI_BUILD_REF_NAME
        - IMAGE_NAME_LATEST=liteacz/cron:latest
        - docker pull $IMAGE_NAME_LATEST || true
        - docker build --cache-from $IMAGE_NAME_LATEST -t $IMAGE_NAME_CURRENT .
        - docker push $IMAGE_NAME_CURRENT
        - if [ ! -z $CI_COMMIT_TAG ]; then
        -   echo "Commit tag set to $CI_COMMIT_TAG, tagging built image as latest."
        -   docker tag $IMAGE_NAME_CURRENT $IMAGE_NAME_LATEST
        -   docker push $IMAGE_NAME_LATEST
        - fi
    only:
        - tags
        - web